version: '2.1'
services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    ports:
      - "5445:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: zorg
      POSTGRES_DB: zorg

  elasticsearch:
    image: build.datapunt.amsterdam.nl:5000/atlas/elasticsearch5
    command: elasticsearch -Enetwork.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"

  zorg:
    build: ./web
    links:
      - database
      - elasticsearch
    ports:
      - "8005:8000"
    environment:
      DATABASE_NAME: zorg
      DATABASE_PASSWORD: insecure
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "zorg.wsgi:application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/static=/static"
      UWSGI_PROCESSES: 4
