version: '3.0'
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5445:5432"
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: zorg
      POSTGRES_DB: zorg

  elasticsearch:
    image: amsterdam/elasticsearch6
    command:  elasticsearch -Ehttp.host=0.0.0.0 -Etransport.host=127.0.0.1
    ports:
      - "9200:9200"
      - "9300:9300"
  zorg:
    build: ./web
    links:
      - database
      - elasticsearch
    ports:
      - "8005:8000"
    environment:
      ELASTICSEARCH_PORT_9200_TCP_ADDR: elasticsearch
      ELASTICSEARCH_PORT_9200_TCP_PORT: 9200
      DATABASE_PORT_5432_TCP_ADDR: database
      DATABASE_PORT_5432_TCP_PORT: 5432
      DATABASE_NAME: zorg
      DATABASE_PASSWORD: insecure
      DATAPUNT_API_URL: ${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "zorg.wsgi:application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/static=/static"
      UWSGI_PROCESSES: 4
