swagger: '2.0'

info:
  version: "1.0.0"
  title: Datapunt Amsterdam Zorg
  description: |
    ## Guid

    Bij het aanmaken van organisaties, locaties en activiteiten genereert de applicatie zelf een `guid` op basis van de gebruiker en de id in de aanroep.

    Indien een `guid` wordt meegestuurd met een `http POSTrequest` wordt deze door het systeem genegeerd en zal het systeem zelf een nieuwe unieke guid genereren.
    Bij `lees`, `update` en `verwijder` opdrachten moet de `guid` wel meegestuurd worden.

    Het gebruik van een guid maakt het mogelijk om meerdere partijen hun eigen id reeks te laten gebruiken zonder dat dit leidt tot conflicten in het zorg-portaal.

    Op termijn is het de bedoeling om ook gebruik te maken van het eigen id voor lees, update en verwijder opdrachten. Dit ligt voorlopig nog buiten de scope van het project.

    ## Authenticatie

    Voor het ophalen van data via een `http GET request` is geen authenticatie nodig.
    Het toevoegen en wijzigen van data vereist echter een API token.

    [Meer informatie over API tokens](https://scotch.io/tutorials/the-ins-and-outs-of-token-based-authentication)

    -en-

    [Hoe deze te implemeteren](http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication).

basePath: /zorg

schemes:
  - https

consumes:
  - application/json

produces:
  - application/json

################################################################################
#                                     Paths                                    #
################################################################################

paths:
  /status/health:
    get:
      tags: [ status ]
      # operationId: health.views.health
      summary: returns ok when server is up
      responses:
        200:
          description: status health check
          schema:
            type: string
        500:
          description: server error
          schema:
            $ref: '#/definitions/error_response'

  /status/data:
    get:
      tags: [ status ]
      summary: returns ok if data is reachable and sane
      # operationId: health.views.data
      responses:
        200:
          description: status health check
          schema:
            type: string
        500:
          description: server error
          schema:
            $ref: '#/definitions/error_response'

  /zoek:
    get:
      tags: [ zoek-endpoint ]
      summary: Zoek
      # operationId: api.ZoekApiView.as_view
      parameters:
      -
        name: query
        in: query
        description: de woorden / delen van woorden waarop gezocht wordt
        type: string
        required: false
      responses:
        200:
          description: Returns a list of search results
          schema:
            type: object
            properties:
              took:
                type: number
                format: int64
              timed_out:
                type: boolean
              _shards:
                type: object
              hits:
                type: array
                items:
                  type: object
                  properties:
                    total:
                      type: number
                      format: int64
                    max_score:
                      type: number
                      format: float
                    hits:
                      type: array
                      items:
                        type: object
        500:
          description: server error
          schema:
            $ref: '#/definitions/error_response'

  /zoek/{search-for}:
    get:
      tags: [ zoek-endpoint ]
      summary: zoek naar `organisatie`, `locatie` of `activiteit`
      # operationId: api.ZoekApiView.as_view
      parameters:
      -
        name: search-for
        in: path
        description: data van het type `organisatie`, `locatie` of `activiteit`
        type: string
        required: true
        enum:
          - organisatie
          - locatie
          - activiteit
      -
        name: query
        in: query
        description: de woorden / delen van woorden waarop gezocht wordt
        type: string
        required: false
      responses:
        200:
          description: Returns a list of search results
          schema:
            type: object
            properties:
              took:
                type: number
                format: int64
              timed_out:
                type: boolean
              _shards:
                type: object
              hits:
                type: array
                items:
                  type: object
                  properties:
                    total:
                      type: number
                      format: int64
                    max_score:
                      type: number
                      format: float
                    hits:
                      type: array
                      items:
                        type: object
        500:
          description: server error
          schema:
            $ref: '#/definitions/error_response'

  /zoek/geo:
    get:
      tags: [ zoek-endpoint ]
      summary: zoek op lat, lon en tekst
      # operationId: api.GeoZoekView.as_view
      parameters:
      -
        name: query
        in: query
        description: de woorden / delen van woorden waarop gezocht wordt
        type: string
        required: false
      -
        name: lat
        in: query
        description: latitude
        required: true
        type: number
      -
        name: lon
        in: query
        description: longitude
        required: true
        type: number
      responses:
        200:
          description: Returns a list of search results
          schema:
            type: object
            properties:
              took:
                type: number
                format: int64
              timed_out:
                type: boolean
              _shards:
                type: object
              hits:
                type: array
                items:
                  type: object
                  properties:
                    total:
                      type: number
                      format: int64
                    max_score:
                      type: number
                      format: float
                    hits:
                      type: array
                      items:
                        type: object

        500:
          description: server error
          schema:
            $ref: '#/definitions/error_response'


  /zoek/thema:
    get:
      tags: [ zoek-endpoint ]
      summary: zoek op thema
      # operationId: TermsZoekView.as_view
      produces:
        - application/json
      parameters:
      -
        name: page
        in: query
        description: pagination the page number to show
        type: number
        format: int64
        required: false

      responses:
        200:
          description: Returns a list of search results
          schema:
            type: object
            properties:
              took:
                type: number
                format: int64
              timed_out:
                type: boolean
              _shards:
                type: object
              hits:
                type: array
                items:
                  type: object
                  properties:
                    total:
                      type: number
                      format: int64
                    max_score:
                      type: number
                      format: float
                    hits:
                      type: array
                      items:
                        type: object
        500:
          description: server error
          schema:
            $ref: '#/definitions/error_response'

  /organisatie:
    get:
      tags: [ data-endpoint ]
      summary: data organisaties
      # operationId: api.datasets.normailzed.views.OrganisatieViewSet
      produces:
        - application/json
      parameters:
      -
        name: page
        in: query
        description: pagination the page number to show
        type: number
        format: int64
        required: false
      responses:
        200:
          description: Returns a list of orgaisatie data
          schema:
            type: object
            properties:
              _links:
                $ref: '#/definitions/_links'
              results:
                type: array
                items:
                  $ref: '#/definitions/results'
        500:
          description: server error
          schema:
            $ref: '#/definitions/error_response'

  /activiteit:
    get:
      tags: [ data-endpoint ]
      summary: data activiteiten
      # operationId: api.datasets.normailzed.views.OrganisatieViewSet
      produces:
        - application/json
      parameters:
      -
        name: page
        in: query
        description: pagination the page number to show
        type: number
        format: int64
        required: false
      responses:
        200:
          description: Returns a list of activiteiten data
          schema:
            type: object
            properties:
              _links:
                $ref: '#/definitions/_links'
              results:
                type: array
                items:
                  $ref: '#/definitions/results'
        500:
          description: server error
          schema:
            $ref: '#/definitions/error_response'

  /locatie:
    get:
      tags: [ data-endpoint ]
      summary: data locatie
      # operationId: api.datasets.normailzed.views.OrganisatieViewSet
      produces:
        - application/json
      parameters:
      -
        name: page
        in: query
        description: pagination the page number to show
        type: number
        format: int64
        required: false
      responses:
        200:
          description: Returns a list of locatie data
          schema:
            type: object
            properties:
              _links:
                $ref: '#/definitions/_links'
              results:
                type: array
                items:
                  $ref: '#/definitions/results'
        500:
          description: server error
          schema:
            $ref: '#/definitions/error_response'


################################################################################
#                                  Definitions                                 #
################################################################################

definitions:

  organisatie:
    type: object
    properties:
      guid:
        type: string
      naam:
        type: string

  locatie:
    type: object
    properties:
      guid:
        type: string
      naam:
        type: string

  activiteit:
    type: object
    required:
      - guid
      - naam
    properties:
      guid:
        type: string
      naam:
        type: string
      beschrijving:
        type: string
      bron_link:
        type: string
      contactpersoon:
        type: string
      personen:
        # link to personen query
        type: string
      tags:
        type: string
      start_time:
        type: string
        format: date-time
      end_time:
        type: string
        format: date-time
      locatie:
        type: string
      organisatie:
        type: string

  persoon:
    type: object
    properties:
      guid:
        type: string
      contact:
        type: string
      naam:
        type: string

  href:
    type: object
    properties:
      href:
        type: string

  _links:
    type: object
    properties:
      self:
        $ref: '#/definitions/href'
      next:
        $ref: '#/definitions/href'
      prev:
        $ref: '#/definitions/href'

  results:
    type: object
    allOf:
      - $ref: '#/definitions/activiteit'
      - $ref: '#/definitions/locatie'
      - $ref: '#/definitions/organisatie'

  error_response:
    type: object
    required:
      - message
      - code
    properties:
      message:
        type: string
      code:
        type: string
