database:
  image: build.datapunt.amsterdam.nl:5000/atlas/postgres
  environment:
    POSTGRES_PASSWORD: insecure
    POSTGRES_USER: zorg
    POSTGRES_DB: zorg

elasticsearch:
  image: build.datapunt.amsterdam.nl:5000/atlas/elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  volumes:
   - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml


zorg:
  build: ../web
  links:
    - database:database
    - elasticsearch:elasticsearch
  ports:
    - "8080:8000"
  environment:
    DATABASE_NAME: zorg
    DATABASE_PASSWORD: insecure
