version: '3.0'
services:
  database:
    image: amsterdam/postgres11
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: zorg
      POSTGRES_DB: zorg

  elasticsearch:
    image: amsterdam/elasticsearch6
    command: elasticsearch -Enetwork.host=0.0.0.0
    volumes:
     - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  zorg:
    build: ../web
    links:
      - database:database
      - elasticsearch:elasticsearch
    ports:
      - "8000:8000"
    environment:
      DATABASE_NAME: zorg
      DATABASE_PASSWORD: insecure
      DATAPUNT_API_URL: ${DATAPUNT_API_URL:-https://api.data.amsterdam.nl/}
